version: '3.1'

services:
  mysql:
    container_name: mysql5
    image: mysql:5.7.24
    restart: always
    volumes:
      - ${MNT_BASE_VOL}/mysql:/var/lib/mysql
      - ${MNT_BASE_VOL}/share:/root/share
    # command
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--skip-character-set-client-handshake',
      ]
    ports:
      - ${MYSQL_EXPOSE_PORT}:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=wgai-db
    logging:
      driver: 'json-file'
      options:
        'max-size': '1G'
    networks:
      - xy-network
      - private

  cache:
    container_name: cache
    image: redis
    restart: always
    privileged: true
    ports:
      - ${REDIS_EXPOSE_PORT}:6379
    command: redis-server --appendonly yes --save 300 10 --requirepass admin123
    volumes:
      - ${MNT_BASE_VOL}/redis:/data
      # - ./cache-conf/redis.conf:/etc/redis/redis.conf
    networks:
      - xy-network
      - private

networks:
  private:
  xy-network:
    name: xy-network
    external: true
